# Generated by Django 4.2.7 on 2024-06-09 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_wishlist_review_productfaq_notification_coupon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productfaq",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Faqs",
                to="store.product",
            ),
        ),
    ]
