# Generated by Django 4.2.7 on 2024-06-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_productfaq_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
