# Generated by Django 4.2.7 on 2024-06-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_product_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                (
                    "rate",
                    models.IntegerField(
                        default=5,
                        help_text="Number added here are in percentage e.g 5%",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
